name: 'customer_cleansing_capstone'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  customer_cleansing_capstone:

    staging:
      +materialized: view
      +schema: STG

    intermediate:
      +materialized: view
      +schema: STG

    marts:
      +materialized: table
      +schema: DWH

seeds:
  customer_cleansing_capstone:
    +schema: STG
    +quote_columns: false